### ISSUE TITLE
Paragraph: Call out box - errors when inserting.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_campaigns#18]
Creating a new campaign page, add call out box, no fields on paragraph type and saving the campaign gives the following error.

`InvalidArgumentException: Field field_button is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of core/lib/Drupal/Core/Entity/ContentEntityBase.php). `

**Comment by stephen-cox** [comment]
Should be fixed by #17
