### ISSUE TITLE
Campaigns: confirm list of paragraph types.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_campaigns#25]
Current paragraphs types available in localgov_campaigns: 

 - Box link
 - Call out box
 - Fact boxes
 - Link and summary
 - quote box
 - Text and image
 - Text field
 - Text (two columns)

This issue needs to:

 - confirm the specification of each of the above paragraphs
 - confirm what other paragraph types are desired for Bracknell Forest / Croydon / BHCC

**Comment by willguv** [comment]
@finnlewis @lbcwebmaster 

Colin has supplied a comparison between LGD and Bracknell Forest page elements at https://drive.google.com/drive/folders/1rJnN5LRWRHIJbmtEpsEl4SytavT-4duS

**Comment by stephen-cox** [comment]
List of paragraph types that will be available to add to campaign pages:

- Box link
- Call out box
- Fact boxes
- Image
- Link and summary
- Quote
- Text
- Video

**Comment by willguv** [comment]
Looks good to me @stephen-cox 

We can always review again before the Bracknell campaigns are brought in
