### ISSUE TITLE
Add 'Content carousel' paragraph type

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [localgovdrupal/localgov_campaigns#37]
Fields:

- Title (plain text, optional)
- Heading level (select list, optional, default h2)
- 1 or more slides (Content carousel slide paragraphs), each with the following fields:
  - Slide layout (two options - Media left, Content right and Content left, Media right)
  - Slide content - entity (node) reference field
  - Read more (on/off checkbox, default on)
  - Read more text (plain text, optional)

Relates to ['Add Bracknell campaign paragraphs' issue](https://github.com/localgovdrupal/localgov/issues/105)

**Comment by keelanfh** [comment]
Closed as module deprecated
