### ISSUE TITLE
Add 'Highlighted' paragraph type

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [localgovdrupal/localgov_campaigns#39]
Fields:
- Icon (select field with a set list of icons, optional) TODO: discuss what's the best way to implement this - where the list of icons should come from
- Content (WYSIWYG, mandatory)

Relates to '[Add Bracknell campaign paragraphs' issue](https://github.com/localgovdrupal/localgov/issues/105)

**Comment by willguv** [comment]
David Hampton suggests font awesome, free or pro

@cjstevens78 font awesome is loaded into the LGD default theme

@stephen-cox we're loading in FA elsewhere, needs some kind of config to limit the choice of icons (do later)

Content designer inputs FA code, use the auto complete functionality that already exists 

@Adnan-cds can give details

**Comment by andybroomfield** [comment]
@willguv @gosia-mlynarczyk Assume it will have to be Font-awesome free as we cannot assume if councils will each have a font awesome pro license so we should make the classes match the free versions for anything distributed.

**Comment by gosia-mlynarczyk** [comment]
@willguv @andybroomfield @stephen-cox @Adnan-cds The Bracknell site actually uses a different font set called [IcoMoon](https://icomoon.io/), so not sure how to proceed with this one. Maybe it doesn't make sense to include this paragraph type in the LocalGov Campaign paragraphs module, as it's quite tied to a theme (and different themes may use different icons)?

**Comment by Adnan-cds** [comment]
Hi Gosia, have you considered adding IcoMoon as an Asset library into the Drupal module for this Paragraph?

FAO @gosia-mlynarczyk

**Comment by stephen-cox** [comment]
Some LocalGov paragraphs are tied to FontAwesome and it's now a dependency of the the core module [1](https://github.com/localgovdrupal/localgov_paragraphs/blob/3e03b3070237d1ecb6995a7e35bcaa639e54b0a9/composer.json#L16). If we want to allow the selection of different icon libraries then we should construct paragraph types to be agnostic about the particular icon library and add the dependency to the theme. If this is something we would like/need to do then we will need to break the current dependencies and implement icon selection in a generic manner.

**Comment by keelanfh** [comment]
Closed as module deprecated. If we want to add things into subsites, I think it's more appropriate to create a new issue.
