### ISSUE TITLE
Add 'Map' paragraph type

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [localgovdrupal/localgov_campaigns#40]
Fields:
- Location (geofield, optional)
- 0 or 1 Directory entry (entity reference field - custom Directory entry entity, optional)

TODO - Check with the team:
the second bullet point depends on having a Directory entry entity. Should this paragraph have this option? Or just the geolocation field? Or should this paragraph be excluded from the LocalGov repo, as it's too Bracknell specific?

Relates to ['Add Bracknell campaign paragraphs' issue](https://github.com/localgovdrupal/localgov/issues/105)

**Comment by willguv** [comment]
@stephen-cox suggest using the LocalGov Geo module as this could make things simpler

**Comment by keelanfh** [comment]
Closed as module deprecated. If we want to add things into subsites, I think it's more appropriate to create a new issue.
