### ISSUE TITLE
Add 'Tabs' paragraph type

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [localgovdrupal/localgov_campaigns#42]
Fields:
- Title (plain text, optional)
- Heading level (select list, optional, default h2)
- 1 or more tab panels (Tab panel paragraphs), each with the following fields:
  - Title (plain text, mandatory)
  - Heading level (select list, optional, default h3)
  - Content (WYSIWYG, mandatory)

Relates to ['Add Bracknell campaign paragraphs' issue](https://github.com/localgovdrupal/localgov/issues/105)

**Comment by finnlewis** [comment]
We think this is done.
