### ISSUE TITLE
Add 'Block reference' paragraph type

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [localgovdrupal/localgov_campaigns#46]
Fields:
- 1 Block (View) reference field (mandatory)

Relates to ['Add Bracknell campaign paragraphs' issue](https://github.com/localgovdrupal/localgov/issues/105)

**Comment by keelanfh** [comment]
Closed as module deprecated. If we want to add things into subsites, I think it's more appropriate to create a new issue.
