### ISSUE TITLE
Review paragraph and field names

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_campaigns#7]
Some of the page builder paragraph types include `page_builder1 in their names; some don't. 
Some paragraph types end in a underscore; we certainly want to rename these.

The fields should only be used by the page builder paragraph types, but they have generic names like `field_image` and `field_link`. Do we want to namespace and so rename all these fields?

**Comment by ekes** [comment]
`field_campaign` and pages should be bought in line with the same overview / landing / parent pattern starting `localgov_` as with services, guides...

**Comment by stephen-cox** [comment]
Are you suggesting all fields should be renamed? I thought we were only doing where necessary.
