### ISSUE TITLE
Rename campaigns to engagement pages / sub-sites 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_campaigns#71]
This is ptentially controversial, but let's take the opportunity to rename the campaigns content types to something more meaningful for a wider range of councils. 

Working with Lambeth, the use of the word 'campaign' to describe the sub-site functionality does not feel right. I think the main issue is that a campaign is seen as something with a limited lifespan. Sub-sites like 'Fostering' and 'Weddings' do not have a limited lifespan so are not really seen as 'campaigns'.

Lambeth call thes 'Engagement pages'.

They have also been called 'sub-sites' or 'microsites'.

It occured to us that it would be relatively easy to rename these content types and this project now as the Lambeth team are just starting to focus on these paegs. 

Two main questions occur: 

1. Would renaming these pages cause a massive headache for anyone else using campaings content type functionality at the present time? I'm thinking perhaps @Adnan-cds @andybroomfield might be making use.

2. If we can rename, what's a more meaninglful name? @ekes @willguv @lbcwebmaster @stephen-cox ?
 - engagement overview / engagement page
 - sub-site overview / sub-site page
 - microsite overview / microsite page

Meanwhile we are also extending the functionality with a nested hierarchy menu navigation and more featured hero banners which I am hoping we can push back up to LocalGov Drupal.

**Comment by stephen-cox** [comment]
We would need to check with London Councils and Bracknell Council to check whether they have installed campaigns into site that can't be easily removed. Perhaps this is something for the Product Group? They could also suggest what it should be called.

These pages have multiple uses and so naming them is always going to be tricky. Perhaps it's easier for councils with specific uses for these to change the display name.

**Comment by willguv** [comment]
Good news on the feature improvements!

The name change need not be controversial, but more people need to see and discuss. Finn, can you or John use the [#new-features process](https://docs.google.com/document/d/1EKA3pN_YanHyjvW7iQ9BDzyDORGLmhKCwQlHEH0-K0I/edit?usp=sharing)? We need to see if it helps or hinders

**Comment by andybroomfield** [comment]
I asume your going to provide an update hook to effect the machine name change.
Can't speak for the comms team / BHCC as a whole, from a tech point of view it should be ok, the migrations will have to be updated, and we are likly to keep the legacy BHCC campaigns around as they are more complicated to migrate.

**Comment by finnlewis** [comment]
Comments from another council: 

> For my two cents, I agree, campaign feels very misleading and wrong - it sounds time-bound.
> I think engagement is the best option because it does what it says on the tin.
> I think subsite is also a good option because it helps convey to services that it gives them a bit of freedom and independence.

**Comment by finnlewis** [comment]
Just to share, my current plan is to create a new project localgov_subsites to port the new functionality and new naming conventions to from the Lambeth Council work. Then we can look to include that with the default LocalGov Drupal installation with suitable migration paths once we've identified that migration paths are definitely needed.

**Comment by finnlewis** [comment]
Here's the first pass: https://github.com/localgovdrupal/localgov_subsites
