### ISSUE TITLE
Update Campaigns' About text and README.md to explain relation to SubSites module

### ISSUE THREAD

**Issue by tebb** [localgovdrupal/localgov_campaigns#76]
Should the About text and README.md be updated to direct people to the 'replacement' module Subsites?

Subsites' About text says:
Replaces LocalGov Campaigns with a new name and extended functionality to support subsites within LocalGov Drupal installations.

Campaigns' About text says:
Provides campaign sections using page builder paragraph types for LocalGov Drupal.
... but does not mention Subsites.

**Comment by andybroomfield** [comment]
Does someone want to add this to the readme? Should we also decomission this module now?

Even if the readme says something to the effect of `The module has been discontinued, please use [localgov_subsite](https://github.com/localgovdrupal/localgov_subsites) instead.`

@finnlewis @tebb @willguv

**Comment by andybroomfield** [comment]
Added PR, once that is merged we should go through the process of archiving this module.
